import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../components/Button'; import { Card } from '../components/Card'; import { CountdownBadge } from '../components/CountdownBadge'; import { PhoneScreen } from '../components/PhoneScreen'; import { ScoreBoard } from '../components/ScoreBoard'; import { TimerBar } from '../components/TimerBar'
import { useLocalGame } from '../client/hooks/useLocalGame'; import { getRemainingSeconds } from '../client/lib/time'; import { validateAnswer } from '../lib/validateAnswer'

export function AnsweringChallengerPage() {
  const navigate = useNavigate(); const { state, actions } = useLocalGame(); const [answer, setAnswer] = useState(''); const [remaining, setRemaining] = useState(() => getRemainingSeconds(state.deadlineAt)); const answerRef = useRef(answer); answerRef.current = answer
  useEffect(() => { let handled = false; const tick = () => { const next = getRemainingSeconds(state.deadlineAt); setRemaining(next); if (!next && !handled) { handled = true; if (validateAnswer(answerRef.current).valid) { actions.submitAnswer(answerRef.current); navigate('/voting') } else { actions.forfeitAnswer(); navigate('/reveal') } } }; tick(); const id = window.setInterval(tick, 250); return () => clearInterval(id) }, [state.deadlineAt, actions, navigate])
  const validation = validateAnswer(answer)
  return <PhoneScreen className="gap-4"><ScoreBoard score={state.score}/><div className="flex justify-end"><CountdownBadge remainingSeconds={remaining}/></div><TimerBar remainingSeconds={remaining} totalSeconds={45}/><Card><p className="text-xs font-bold text-neutral-400">お題</p><p className="mt-1 text-lg font-bold">「{state.round?.prompt.text}」</p></Card><div><span className="mb-1 block text-sm font-bold">あなたの回答</span><textarea value={answer} rows={2} maxLength={60} onChange={(event) => setAnswer(event.target.value.replace(/[\r\n]/g, ''))} className="w-full resize-none rounded-[13px] border-2 border-[#c7c2b8] bg-white px-4 py-3"/><p className="mt-1 text-right text-xs text-neutral-400">{Array.from(answer).length}/60</p>{!validation.valid && answer.length > 0 && <p className="text-xs text-rose-500">{validation.message}</p>}</div><div className="mt-auto"><Button disabled={!validation.valid} onClick={() => { actions.submitAnswer(answer); navigate('/voting') }}>回答を確定する</Button></div></PhoneScreen>
}
